### ISSUE TITLE
Sample app with-Broker is working without broker app(Microsoft authenticator) in phone

### ISSUE THREAD

**Issue by viveknegi51288** [Azure-Samples/active-directory-xamarin-native-v2#139]
Hi,
I do not have authenticator app in my testing device, I have downloaded this project and try to run the with-broker project in ios, 

Behavior - Initially it ask for email id and password and then it able to get token value.

Expected behavior - If testing device doesn't have authenticator app, the application should not work.

Question _ Why this sample app with broker working even if mobile doesnt have authenticator application install

**Comment by jmprieur** [comment]
Which button of the UI did you use, @viveknegi51288 ?

**Comment by viveknegi51288** [comment]
Sign in with broker

**Comment by jmprieur** [comment]
@tawalke @aiwangmicrosoft

**Comment by viveknegi51288** [comment]
@tawalke @aiwangmicrosoft  please help

**Comment by tawalke** [comment]
@trwalke I think this was for you. 
@jamesmontemagno just in case you have insight.

**Comment by viveknegi51288** [comment]
@trwalke  and @jamesmontemagno , @aiwangmicrosoft @jmprieur  please help....

**Comment by viveknegi51288** [comment]
@trwalke @aiwangmicrosoft @jmprieur @jairomontes-microsoft

**Comment by jennyf19** [comment]
@viveknegi51288 The sample is working without broker installed because the user signing in does not have conditional access policies applied to it, so signing in with a broker is not required. If the user is not required to have broker, then we will take them through a regular sign-in experience (showing the UI and signing-in). If broker is required, they will be guided through the registration process of downloading broker for either the Apple or Google Play Store respectively.

@aiwangmicrosoft i don't think we have this clearly documented as far as customer experience.

cc: @henrik-me

**Comment by bgavrilMS** [comment]
@aiwangmicrosoft - any progress on this?

**Comment by jennyf19** [comment]
closing as the issue seems to be addressed. @viveknegi51288 reopen or open another if you disagree. thank you.
