### ISSUE TITLE
Build fails on Debug mode -> Error: Could not find any available provisioning profiles for UserDetailsClientiOS on iOS

### ISSUE THREAD

**Issue by kgbuddhima** [Azure-Samples/active-directory-xamarin-native-v2#163]
When I was trying to build the sample app on Debug|iPhoneSimulator mode, I'm having following error.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(3,3): **Error: Could not find any available provisioning profiles for UserDetailsClientiOS on iOS.**
         (UserDetailsClient.iOS)

I found this github issue too. 
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/123

But I want to know can't I build the app on debug mode without a provisioning profile? 

So how can I overcome this issue?

I didn't make any changes to the sample project's packages. the only changes that I did was adding my client keys and bundleId(s).

**Comment by jmprieur** [comment]
@kgbuddhima which sample app?  https://github.com/Azure-Samples/active-directory-xamarin-native-v2 ?
@trwalke : do you mind having a look, please?

**Comment by kgbuddhima** [comment]
> @kgbuddhima which sample app? https://github.com/Azure-Samples/active-directory-xamarin-native-v2 ?
> @trwalke : do you mind having a look, please?

Yes.

**Comment by trwalke** [comment]
@kgbuddhima All iOS apps require a provisioning profile in order to build and as long as you are connected to a mac(or building from a mac) with the installed provisioning profile you can build the application. You can download your provisioning profiles from your apple account by following these [steps](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=windows) 

There is an easier way to resolve the issue by using automatic provisioning [here](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows)

**Comment by kgbuddhima** [comment]
> @kgbuddhima All iOS apps require a provisioning profile in order to build and as long as you are connected to a mac(or building from a mac) with the installed provisioning profile you can build the application. You can download your provisioning profiles from your apple account by following these [steps](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=windows)
> 
> There is an easier way to resolve the issue by using automatic provisioning [here](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows)

Thank you @trwalke

**Comment by kgbuddhima** [comment]
Issue solved after install the necessary provisioning profile.
