### ISSUE TITLE
Local account

### ISSUE THREAD

**Issue by Surfrat** [Azure-Samples/active-directory-xamarin-native-v2#27]
Can you please add local account access like v1 of this project?

Thanks

Surfrat.

**Comment by jmprieur** [comment]
@Surfrat : what do you mean a local account? this is about signing-in with Azure Active directory. There is no local account. Are you looking for windows integrated security?

**Comment by Surfrat** [comment]
No your previous sample v1 has a AD local account.... Why are you closing everything before I even have a chance to respond!

**Comment by jmprieur** [comment]
I understand why you mean @Surfrat based on your other question, and replied here: https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/26#issuecomment-386281405

This is not an Azure B2C sample, and therefore is not mean to have a local account.

I closed the issue because it was not relevant to the sample, but this does not prevent me from monitoring (and answering) your questions / replies, as you can see. Sorry if I gave you the impression that I was not interested. I'll let you close the other issue if you are happy with my answer.
