### ISSUE TITLE
Xamarin.Forms.Android OnActivityResult is never called

### ISSUE THREAD

**Issue by TomWalkerCodes** [Azure-Samples/active-directory-xamarin-native-v2#28]
Good day,

We recently upgraded our XF project to MSAL to ver1.1.2.  We have no issues with getting the iOS client working.  We were unable to get passed the MSAL login page on the Android client.  I noticed that the OnActivityResult method is never firing prior to the login screen appearing.  I can only trigger the method call when I back out from the login screen.  I know the MSAL configuration works because the iOS client can login successfully.   I did update the Android manifest to match the example.  I did update the file to use our Application ID.  Is it important to set the the UIParent context after the LoadApplication(new App()) ?   We have it set prior to this line because we want to have the login screen appear right on app startup.

**Comment by jmprieur** [comment]
@TomWalkerCodes : 
2 things at the top of my mind:
1. did you setup the callback to call MSAL back (SetAuthenticationContinuationEventArgs) as done in this line:
https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs#L29

2. would you be using .Result instead of await ?

**Comment by jmprieur** [comment]
@TomWalkerCodes : I'm assuming you have solved your problem. 
Closing for now. Feel free to reopen if you still face issues
