### ISSUE TITLE
Broken on Android 4.4

### ISSUE THREAD

**Issue by bryans2k** [Azure-Samples/active-directory-xamarin-native-v2#54]
I can log-in on Android 4.4 but when it tries to return to the app it just displays the app with a blank screen. It seems to work without a problem on Android 8.1.

**Comment by jmprieur** [comment]
@bryans2k 
- Which version of MSAL do you use? MSAL 4.2.0 as in the sample?
- Is it a new problem? or is it the first time you try it on Android 4.4?
- which model of phone do you use? Is Chome installed? otherwise what is the browser? Did you see: this page: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Android-system-browser ?

cc; @jennyf19

**Comment by bryans2k** [comment]
I just downloaded the sample exactly as is so it uses 2.4.0-preview. I only changed the clientId in App.cs. It's the first time I tried it. I tried it on a Android 4.4 AVD and Android 8.1 AVD. Chrome is used. Yeah, I read about it but it's just using Chrome as it's a fresh image.

**Comment by bryans2k** [comment]
Opened there as:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/685

**Comment by jmprieur** [comment]
Closing as a tracking issue in MSAL.NET as this is not specific to this sample.
Thanks @bryans2k
