### ISSUE TITLE
Clear browser cookies after logout 

### ISSUE THREAD

**Issue by KyrillosS25** [Azure-Samples/active-directory-xamarin-native-v2#86]
Logout() removes all authenticated account from active directory , but the account is still signed in in the browser  
`
IEnumerable<IAccount> accounts = await App.PCA.GetAccountsAsync();
            
while (accounts.Any())
            {
                await App.PCA.RemoveAsync(accounts.FirstOrDefault());
                accounts = await App.PCA.GetAccountsAsync();
            }
`
![image](https://user-images.githubusercontent.com/56297254/66383215-e82e9080-e9bc-11e9-9c58-faf98cfaa35c.png)

so I need to logout the user from the browser too

**Comment by DiegoFaFe** [comment]
Does this also occurs with the embedded webview?

**Comment by KyrillosS25** [comment]
yes, but i found code to clear cookies in embedded webview and doesn't work for chrome
`CookieManager cookieManager = CookieManager.Instance;

            cookieManager.RemoveAllCookie();
            cookieManager.RemoveSessionCookie();
            cookieManager.Flush();`

**Comment by jennyf19** [comment]
@KyrillosS25 MSAL does not handle the cookies, but i also noticed the same issue you show above when testing earlier this week on iOS 13. Will log a bug on the server and update here. Thank you.

**Comment by jennyf19** [comment]
@KyrillosS25 which platform do you see this on? i was only seeing it on iOS 13, not Android.

**Comment by KyrillosS25** [comment]
@jennyf19  
I am using Android 8.1 - API 27

**Comment by sagarmp02** [comment]
I am also facing the same problem?. I am using xamarin forms as my project and I am testing on android. Any solution?

**Comment by rodrigordi** [comment]
Maybe should be necessary clear cookies before login ?

**Comment by sagarmp02** [comment]
@rodrigordi I tried clearing before login still it is not asking for the password.

**Comment by rodrigordi** [comment]
@sagarmp02 how did you do that ? using cookieManager ?
I think the problem could be because the cookie is on navigator (chrome) and not on webview. When I manually cleared data on chrome (using settings, privacy, clear data), login asked me for the password.

This problem happen with AAD, Facebook, Google. I've not tried with the others authproviders.

**Comment by TiagoBrenck** [comment]
I think this subject is a little bit polemic. IMHO, this is not a MSAL bug and the library shouldn't disconnect you from you authprovider, but from the app only. If you want your app to drop your session from the authprovider, then this must be done in a custom code. 

Lets have this example, where I have a MSAL mobile app that uses gmail account o sign in. Then I sign out, and MSAL drops all my gmail sessions. I then notice that I have stopped receiving emails, all my other apps stopped pushing me notifications, and when I try to open one of them, I figure out that I needed to login with gmail again. And then I would think: "how dare you MSAL to disconnect me from all these other apps?"  

I found [an interesting answer on StackOverflow](https://stackoverflow.com/questions/12909332/how-to-logout-of-an-application-where-i-used-oauth2-to-login-with-google) about this topic. What do you think @jennyf19 @jmprieur ?

**Comment by jmprieur** [comment]
@KyrillosS25 @DiegoFaFe @sagarmp02 @rodrigordi 

@TiagoBrenck is right that your app should not impose sign-out on other apps without the user realizing. There is an experience with Azure Active directory where the user can click on the .... on the right of the tile showing the identity of the user and selection forget. That's the recommended way.

Now we also agree that there are other important scenarios, such as the case where several users share the same device and have to sign-in for a shift at work, and have to sign-out at the end of the shift. Are you in such scenarios? Could you please tell us more about what you are trying to achieve and how the lack of full sign-out is blocking your scenarios?
cc: @TiagoBrenck @jennyf19

**Comment by rodrigordi** [comment]
@TiagoBrenck now you saying this, make all sense for me. I have not thought that the user is not logged in our app only and yes, they are logged in on theirs auth providers (fb, google, aad, etc..) and we are using this to know who they are.

By the way, as @jmprieur  sayed, I have cases where multiples user have to shared the same device by the shift of work.
Another case is if the user wants to complete sign-out of this device without have to open chrome and clear cache data. 

Now, it is clear for me.
Using a browser, when I call <app>/.auth/login, in fact I am doing a sign-in to app without use password because I am signed on my authprovider (AAD) already.
And when I call <app>/.auth/logout, I am signing-out of my provider and not just of my app.

**Comment by TiagoBrenck** [comment]
This might be a good sample scenario then. We could elaborate a new sample to cover logout on shared devices. It is an interesting topic that definitely needs to be exemplified.

**Comment by jmprieur** [comment]
@TiagoBrenck : there is work in progress for these specific scenarios, which are supported in MSAL.iOS and MSAL.Android native. Let's not have a sample for that, as this would come to all MSALs.

**Comment by Coder-RKV** [comment]
@jmprieur was this ever implemented? where can I track enhancements?

**Comment by jmprieur** [comment]
No, not yet @Coder-RKV 
cc: @brandwe
